-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS users (
                                     id INT GENERATED BY DEFAULT AS IDENTITY,
                                     username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username)
    );

-- 2. Create Highscores Table (Relational to Users)
CREATE TABLE IF NOT EXISTS highscores (
                                          id INT GENERATED BY DEFAULT AS IDENTITY,
                                          user_id INT NOT NULL,
                                          score INT NOT NULL,
                                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          PRIMARY KEY (id),
    CONSTRAINT fk_highscores_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );

-- 3. Set up Auto-Updating Timestamp Triggers
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

-- 4. Seed Initial Data
-- Passwords are SHA-256 hashed. 'admin123' and 'player123'
INSERT INTO users (username, password_hash) VALUES
                                                ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9'),
                                                ('player1', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3');

INSERT INTO highscores (user_id, score) VALUES
                                            (1, 150),
                                            (1, 220),
                                            (2, 90);